name: file operatioons in github without checkout

on: workflow_dispatch

jobs:
    files:
        runs-on: ubuntu-latest
        steps:
            -   name: checkout the repo
                uses: actions/checkout@v6

            -   name: display the content of a file
                run:  cat f1.txt

            -   name: display the date
                run: date

            -   name: chenge the permissions
                run: chmod -x uptime.sh
                
            -   name: executing the shell script
                run: ./uptime.sh

